# Generated by Django 3.2.5 on 2021-07-18 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('username', models.CharField(max_length=255, verbose_name='Username')),
                ('followers', models.IntegerField(verbose_name='Followers')),
                ('following', models.IntegerField(verbose_name='Following')),
                ('stars', models.IntegerField(verbose_name='Stars')),
                ('location', models.CharField(max_length=255, verbose_name='Location')),
                ('repositories', models.IntegerField(verbose_name='Repositories')),
                ('contributions', models.IntegerField(verbose_name='Сontributions in the last year')),
                ('profile_link', models.CharField(max_length=255, verbose_name='Profile link')),
            ],
        ),
    ]
