# Generated by Django 3.2.5 on 2021-07-18 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DataBaseSync', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='description',
            field=models.CharField(default='', max_length=255, verbose_name='Description'),
            preserve_default=False,
        ),
    ]
