# Generated by Django 3.2.5 on 2021-08-12 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DataBaseSync', '0003_auto_20210718_1224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='profile_link',
            field=models.CharField(db_index=True, max_length=255, unique=True, verbose_name='Profile link'),
        ),
        migrations.AlterField(
            model_name='member',
            name='username',
            field=models.CharField(db_index=True, max_length=255, unique=True, verbose_name='Username'),
        ),
    ]
